name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: "master"
    - name: Auth
      run: |
        docker login -u densuke -p "${{ secrets.PASS_D }}"
    - name: Build and Push
      run: |
        docker buildx create --use --name builder --driver docker-container
        docker buildx build --platform linux/amd64,linux/arm64 --push -t densuke/sphinx-pdf .
