name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: "master"
    - name: Auth
      run: |
        docker login -u densuke -p "${{ secrets.PASS_D }}"
    - name: Build
      run: |
        docker build -t densuke/sphinx-pdf:arm64 .
    - name: Push
      run: |
        docker push densuke/sphinx-pdf:arm64