name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: "master"
    - name: Auth
      run: |
        echo "${{ secrets.PASS_D }}" | docker login -u densuke --password-stdin
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Build and Push
      run: |
        docker buildx build --platform linux/arm64,linux/amd64 --push -t densuke/sphinx-pdf .
