name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: "master"
    - name: Auth
      run: |
        docker login -u densuke -p "${{ secrets.PASS_D }}"
    - name: Build and Push
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --push -t densuke/sphinx-pdf .
